DELETE FROM conocimiento;

INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (1,'DotNet Framework');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (2,'DotNet Core');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (3,'Entity Framework 6');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (4,'ADO .NET');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (5,'Web API 2');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (6,'Web Forms');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (7,'SQL Server');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (8,'MySQL');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (9,'Postgres');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (10,'Oracle');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (11,'Java');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (12,'Spring MVC');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (13,'Spring Security');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (14,'Primefaces');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (15,'AngularJS');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (16,'Angular');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (17,'ReactJS');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (18,'Android');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (19,'Swift');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (20,'Python');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (21,'Django');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (22,'Objetcive-C');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (23,'C++');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (24,'C#');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (25,'VB .NET');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (26,'HTML5');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (27,'CSS3');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (28,'Javascript');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (29,'Knockout.js');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (30,'Scrum');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (31,'XP');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (32,'PMI');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (33,'Azure');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (34,'AWS');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (35,'Google Cloud');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (36,'Jenkins');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (37,'IIS');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (38,'Linux');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (39,'Windows');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (40,'MacOS');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (41,'Tensorflow.js');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (42,'Artificial Inteligence');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (43,'Business Intelligence');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (44,'Hadoop');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (45,'Continous Integration');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (46,'Domain Driven Design');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (47,'Test Driven Design');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (48,'Restful');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (49,'Programación Orientada Objetos');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (50,'Programación Orientada Aspectos');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (51,'SOLID');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (52,'4 of Gangs');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (53,'P of EAA');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (54,'VIPER');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (55,'Onion Arquitecture');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (56,'Firebase');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (57,'Kotlin');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (58,'Coredata');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (59,'Sqlite');
INSERT INTO conocimiento (IdConocimiento,Descripcion) VALUES (60,'Clean Arquitecture');
