DELETE FROM [dbo].[Pregunta];
-- 1) What is Machine Learning
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('What is Machine Learning?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'What is Machine Learning'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('What is Training Data in ML?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'What is Machine Learning'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('What are the advantages of ML?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'What is Machine Learning'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('How do you know if a problem can be solved by ML Algorthms?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'What is Machine Learning'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('What is the theory related with Machine Learning Algorithms?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'What is Machine Learning'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Question 1', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'What is Machine Learning'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Question 2', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'What is Machine Learning'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Question 3', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'What is Machine Learning'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Question 4', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'What is Machine Learning'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Question 5', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'What is Machine Learning'))
-- 2) History of Machine Learning
     INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 2 - What is Machine Learning?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'History of Machine Learning'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 2 - What is Training Data in ML?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'History of Machine Learning'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 2 - What are the advantages of ML?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'History of Machine Learning'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 2 - How do you know if a problem can be solved by ML Algorthms?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'History of Machine Learning'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 2 - What is the theory related with Machine Learning Algorithms?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'History of Machine Learning'))
-- 3) Machine Learning to Other Fields
     INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 3 - What is Machine Learning?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'Machine Learning to Other Fields'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 3 - What is Training Data in ML?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'Machine Learning to Other Fields'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 3 - What are the advantages of ML?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'Machine Learning to Other Fields'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 3 - How do you know if a problem can be solved by ML Algorthms?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'Machine Learning to Other Fields'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 3 - What is the theory related with Machine Learning Algorithms?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'Machine Learning to Other Fields'))
-- 4) Machine Learning Approaches
     INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 4 - What is Machine Learning?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'Machine Learning Approaches'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 4 - What is Training Data in ML?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'Machine Learning Approaches'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 4 - What are the advantages of ML?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'Machine Learning Approaches'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 4 - How do you know if a problem can be solved by ML Algorthms?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'Machine Learning Approaches'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 4 - What is the theory related with Machine Learning Algorithms?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'Machine Learning Approaches'))
-- 5) Machine Learning Applications
     INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 5 - What is Machine Learning?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'Machine Learning Applications'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 5 - What is Training Data in ML?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'Machine Learning Applications'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 5 - What are the advantages of ML?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'Machine Learning Applications'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 5 - How do you know if a problem can be solved by ML Algorthms?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'Machine Learning Applications'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 5 - What is the theory related with Machine Learning Algorithms?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'Machine Learning Applications'))
-- 6) ML Limitations
     INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 6 - What is Machine Learning?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'ML Limitations'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 6 - What is Training Data in ML?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'ML Limitations'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 6 - What are the advantages of ML?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'ML Limitations'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 6 - How do you know if a problem can be solved by ML Algorthms?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'ML Limitations'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 6 - What is the theory related with Machine Learning Algorithms?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'ML Limitations'))
-- 7) ML Others - Model Assesments, Ethics, Hardware, Software
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 7 - What is Machine Learning?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'ML Others - Model Assesments, Ethics, Hardware, Software'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 7 - What is Training Data in ML?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'ML Others - Model Assesments, Ethics, Hardware, Software'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 7 - What are the advantages of ML?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'ML Others - Model Assesments, Ethics, Hardware, Software'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 7 - How do you know if a problem can be solved by ML Algorthms?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'ML Others - Model Assesments, Ethics, Hardware, Software'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 7 - What is the theory related with Machine Learning Algorithms?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'ML Others - Model Assesments, Ethics, Hardware, Software'))
-- 8) ML Miscellaneous
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 8 - What is Machine Learning?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'ML Miscellaneous'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 8 - What is Training Data in ML?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'ML Miscellaneous'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 8 - What are the advantages of ML?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'ML Miscellaneous'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 8 - How do you know if a problem can be solved by ML Algorthms?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'ML Miscellaneous'))
INSERT INTO [dbo].[Pregunta] ([Descripcion], [Imagen], [IdLeccion])
     VALUES ('Lesson 8 - What is the theory related with Machine Learning Algorithms?', '', (SELECT IdLeccion FROM Leccion Where Nombre like 'ML Miscellaneous'))
