DELETE FROM Respuesta;
-- 1 - 1) Question 1
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer A', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 1'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 1'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 1'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 1'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 1'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
-- 1 - 1) Question 2
VALUES('Correct Answer A', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 2'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 2'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 2'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 2'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 2'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
-- 1 - 1) Question 3
VALUES('Correct Answer A', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 3'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 3'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 3'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 3'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 3'))
-- 1 - 1) Question 4
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer A', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 4'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 4'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 4'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 4'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 4'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
-- 1 - 1) Question 5
VALUES('Correct Answer A', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 5'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 5'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 5'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 5'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Question 5'))
-- 1 - 1) What is Machine Learning?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer A', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'What is Machine Learning?'))
-- 1 - 2) What is Training Data in ML?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer B', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'What is Training Data in ML?'))
-- 1 - 3) What are the advantages of ML?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer C', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'What are the advantages of ML?'))
-- 1 - 4) How do you know if a problem can be solved by ML Algorthms?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer D', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'How do you know if a problem can be solved by ML Algorthms?'))
-- 1 - 5) What is the theory related with Machine Learning Algorithms?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer E', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'What is the theory related with Machine Learning Algorithms?'))

-- 1 - 1) What is Machine Learning?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer A', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - What is Machine Learning?'))
-- 1 - 2) What is Training Data in ML?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer B', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - What is Training Data in ML?'))
-- 1 - 3) What are the advantages of ML?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer C', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - What are the advantages of ML?'))
-- 1 - 4) How do you know if a problem can be solved by ML Algorthms?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer D', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - How do you know if a problem can be solved by ML Algorthms?'))
-- 1 - 5) What is the theory related with Machine Learning Algorithms?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer E', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 2 - What is the theory related with Machine Learning Algorithms?'))

-- 1 - 1) What is Machine Learning?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer A', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - What is Machine Learning?'))
-- 1 - 2) What is Training Data in ML?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer B', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - What is Training Data in ML?'))
-- 1 - 3) What are the advantages of ML?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer C', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - What are the advantages of ML?'))
-- 1 - 4) How do you know if a problem can be solved by ML Algorthms?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer D', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - How do you know if a problem can be solved by ML Algorthms?'))
-- 1 - 5) What is the theory related with Machine Learning Algorithms?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer E', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 3 - What is the theory related with Machine Learning Algorithms?'))

-- 1 - 1) What is Machine Learning?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer A', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - What is Machine Learning?'))
-- 1 - 2) What is Training Data in ML?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer B', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - What is Training Data in ML?'))
-- 1 - 3) What are the advantages of ML?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer C', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - What are the advantages of ML?'))
-- 1 - 4) How do you know if a problem can be solved by ML Algorthms?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer D', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - How do you know if a problem can be solved by ML Algorthms?'))
-- 1 - 5) What is the theory related with Machine Learning Algorithms?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer E', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 4 - What is the theory related with Machine Learning Algorithms?'))

-- 1 - 1) What is Machine Learning?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer A', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - What is Machine Learning?'))
-- 1 - 2) What is Training Data in ML?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer B', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - What is Training Data in ML?'))
-- 1 - 3) What are the advantages of ML?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer C', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - What are the advantages of ML?'))
-- 1 - 4) How do you know if a problem can be solved by ML Algorthms?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer D', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - How do you know if a problem can be solved by ML Algorthms?'))
-- 1 - 5) What is the theory related with Machine Learning Algorithms?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer E', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 5 - What is the theory related with Machine Learning Algorithms?'))

-- 1 - 1) What is Machine Learning?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer A', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - What is Machine Learning?'))
-- 1 - 2) What is Training Data in ML?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer B', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - What is Training Data in ML?'))
-- 1 - 3) What are the advantages of ML?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer C', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - What are the advantages of ML?'))
-- 1 - 4) How do you know if a problem can be solved by ML Algorthms?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer D', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - How do you know if a problem can be solved by ML Algorthms?'))
-- 1 - 5) What is the theory related with Machine Learning Algorithms?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer E', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 6 - What is the theory related with Machine Learning Algorithms?'))

-- 1 - 1) What is Machine Learning?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer A', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - What is Machine Learning?'))
-- 1 - 2) What is Training Data in ML?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer B', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - What is Training Data in ML?'))
-- 1 - 3) What are the advantages of ML?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer C', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - What are the advantages of ML?'))
-- 1 - 4) How do you know if a problem can be solved by ML Algorthms?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer D', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - How do you know if a problem can be solved by ML Algorthms?'))
-- 1 - 5) What is the theory related with Machine Learning Algorithms?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer E', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 7 - What is the theory related with Machine Learning Algorithms?'))

-- 1 - 1) What is Machine Learning?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer A', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - What is Machine Learning?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - What is Machine Learning?'))
-- 1 - 2) What is Training Data in ML?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer B', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - What is Training Data in ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - What is Training Data in ML?'))
-- 1 - 3) What are the advantages of ML?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer C', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - What are the advantages of ML?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - What are the advantages of ML?'))
-- 1 - 4) How do you know if a problem can be solved by ML Algorthms?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer D', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - How do you know if a problem can be solved by ML Algorthms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer E', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - How do you know if a problem can be solved by ML Algorthms?'))
-- 1 - 5) What is the theory related with Machine Learning Algorithms?
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer A', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer B', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer C', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Wrong Answer D', 0, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - What is the theory related with Machine Learning Algorithms?'))
INSERT INTO [dbo].[Respuesta]([Descripcion],[EsCorrecto],[IdPregunta])
VALUES('Correct Answer E', 1, (SELECT IdPregunta FROM Pregunta Where Descripcion like 'Lesson 8 - What is the theory related with Machine Learning Algorithms?'))